services:

  rag-engine:

    build: .

    ports:
      - "8000:8000"

    volumes:
      - ./data:/app/data
      # Mount your AWS credentials
      # Linux/macOS:
      # - ${HOME}/.aws:/home/appuser/.aws:ro

      # Windows:
      - ${USERPROFILE}\.aws:/home/appuser/.aws:ro
      - ./logs:/app/logs

    env_file:
      - .env