from pydantic import BaseModel, Field

from src.core.latency import LatencyReport


class ChatRequest(BaseModel):
    """
    Incoming request for the chat endpoint.
    """

    question: str = Field(
        ...,
        description="User question.",
        examples=["What are the prerequisites for the RAG evaluation pipeline?"],
    )


class SourceResponse(BaseModel):
    """
    Supporting document used to answer the question.
    """

    document: str = Field(
        ...,
        description="Source document used to generate the answer.",
    )

    page: int = Field(
        ...,
        description="Page number in the source document.",
    )

    score: float = Field(
        ...,
        description="Retrieval relevance score after reranking.",
    )


class ChatResponse(BaseModel):
    """
    Response returned by the chat endpoint.
    """

    answer: str = Field(
        ...,
        description="Final answer generated by the RAG pipeline.",
    )

    rewritten_question: str = Field(
        ...,
        description="Query after conversational rewriting and normalization.",
    )

    sources: list[SourceResponse] = Field(
        ...,
        description="Supporting source documents used to generate the answer.",
    )

    latency: LatencyReport = Field(
        ...,
        description="Latency breakdown for each stage of the RAG pipeline.",
    )
