from pydantic import BaseModel, Field

from src.core.latency import LatencyReport


class ChatRequest(BaseModel):
    """
    Incoming request for the chat endpoint.
    """

    question: str = Field(
        ...,
        description="User question.",
        examples=["What is Amazon SageMaker?"],
    )


class SourceResponse(BaseModel):
    """
    Supporting document used to answer the question.
    """

    document: str
    page: int
    score: float = Field(
        ...,
        description="Retrieval relevance score.",
    )


class ChatResponse(BaseModel):
    """
    Response returned by the chat endpoint.
    """

    answer: str = Field(
        ...,
        description="Final answer generated by the RAG pipeline.",
    )

    rewritten_question: str = Field(
        ...,
        description="Question after conversational query rewriting.",
    )

    sources: list[SourceResponse] = Field(
        ...,
        description="Supporting document citations.",
    )

    latency: LatencyReport = Field(
        ...,
        description="Latency of every steps.",
    )
