# settings.py

EMBEDDING_MODEL = "sentence-transformers/all-MiniLM-L6-v2"
RERANKER_MODEL = "BAAI/bge-reranker-base"

LLM_PROVIDER = "openai"
LLM_MODEL = "gpt-4.1-mini"

CHUNK_SIZE = 400
CHUNK_OVERLAP = 100
MAX_CONTEXT_TOKENS = 3000

TOP_K = 5

DENSE_WEIGHT = 0.7
BM25_WEIGHT = 0.3

RETRIEVAL_TOP_K = 30
MAX_RERANK_CANDIDATES = 20
FINAL_TOP_K = 5
NUM_MULTI_QUERIES = 4
QUERY_REWRITE_HISTORY = 4
