from fastapi import APIRouter, Depends
from fastapi.responses import StreamingResponse

from src.api.dependencies import get_chat_engine
from src.api.schemas.chat import ChatRequest, ChatResponse, SourceResponse
from src.chat.chat_engine import ChatEngine

router = APIRouter(
    prefix="/chat",
    tags=["Chat"],
)


@router.post(
    "",
    response_model=ChatResponse,
    summary="Generate an answer using the RAG pipeline",
    description="""
Answers a user question using the complete Retrieval-Augmented Generation pipeline.

The workflow includes:

- Query rewriting
- Multi-query generation
- Hybrid retrieval using BM25 and FAISS
- CrossEncoder reranking
- Context-aware prompt construction
- Response generation using AWS Bedrock Nova Lite
""",
    response_description=(
        "Generated answer with the rewritten question, supporting sources, "
        "and latency metrics."
    ),
)
def chat(
    request: ChatRequest,
    engine: ChatEngine = Depends(get_chat_engine),
) -> ChatResponse:
    """
    Answers a user question using the RAG pipeline.
    """

    result = engine.chat(
        request.question,
    )

    return ChatResponse(
        answer=result.answer,
        rewritten_question=result.rewritten_question,
        sources=[
            SourceResponse(
                document=source.chunk.source,
                page=source.chunk.page_number,
                score=source.score,
            )
            for source in result.retrieved_chunks
        ],
        latency=result.latency,
    )


@router.post(
    "/stream",
    summary="Stream an answer using the RAG pipeline",
    description="""
Streams the generated response incrementally using Server-Sent Events.

The endpoint executes the same RAG workflow as the standard chat endpoint,
but returns the model output as it is generated.
""",
    response_description="Streaming text response generated by the RAG pipeline.",
)
def chat_stream(
    request: ChatRequest,
    engine: ChatEngine = Depends(get_chat_engine),
):
    """
    Streams the LLM response token-by-token.
    """

    return StreamingResponse(
        engine.ask(request.question),
        media_type="text/event-stream",
    )
