from fastapi import APIRouter, Depends, HTTPException
from fastapi.responses import StreamingResponse

from src.api.dependencies import get_rag_engine
from src.api.schemas.chat import ChatRequest, ChatResponse, SourceResponse
from src.app.rag_engine import RAGEngine

router = APIRouter(
    prefix="/chat",
    tags=["Chat"],
)


@router.post(
    "",
    response_model=ChatResponse,
    summary="Generate an answer using the RAG pipeline",
    description="""
Answers a user question using the complete Retrieval-Augmented Generation pipeline.

## The workflow includes:
- Query rewriting
- Multi-query generation
- Hybrid retrieval using BM25 and FAISS
- CrossEncoder reranking
- Context-aware prompt construction
- Response generation using AWS Bedrock Nova Lite

## Demo Knowledge Base
    This project ships with a **pre-built knowledge base** created from the **Amazon SageMaker User Guide**.

## Try these questions:
- "What is Amazon SageMaker?",
- "What are the prerequisites for Amazon SageMaker?"
- "What is the Lakehouse architecture?"
- "What frameworks are supported for data processing?"
- "What data sources can SageMaker connect to?"
""",
    response_description=(
        "Generated answer with the rewritten question, supporting sources, "
        "and latency metrics."
    ),
)
def chat(
    request: ChatRequest,
    engine: RAGEngine = Depends(get_rag_engine),
) -> ChatResponse:
    """
    Answers a user question using the RAG pipeline.
    """

    if not engine.is_ready:
        raise HTTPException(
            status_code=409,
            detail="Knowledge base is empty. Please upload and ingest a document before chatting.",
        )

    result = engine.chat(
        request.question,
    )

    return ChatResponse(
        answer=result.answer,
        rewritten_question=result.rewritten_question,
        sources=[
            SourceResponse(
                document=source.chunk.source,
                page=source.chunk.page_number,
                score=source.score,
            )
            for source in result.retrieved_chunks
        ],
        latency=result.latency,
    )


@router.post(
    "/stream",
    summary="Stream an answer using the RAG pipeline",
    description="""
Streams the generated response incrementally using Server-Sent Events.

The endpoint executes the same RAG workflow as the standard chat endpoint,
but returns the model output as it is generated.
""",
    response_description="Streaming text response generated by the RAG pipeline.",
)
def chat_stream(
    request: ChatRequest,
    engine: RAGEngine = Depends(get_rag_engine),
):
    """
    Streams the LLM response token-by-token.
    """
    if not engine.is_ready:
        raise HTTPException(
            status_code=409,
            detail="Knowledge base is empty. Please upload and ingest a document before chatting.",
        )

    return StreamingResponse(
        engine.ask(request.question),
        media_type="text/event-stream",
    )
